# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "foreman_ovirt"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Oved Ourfali"]
  s.date = "2012-12-20"
  s.description = "Foreman oVirt plugin"
  s.email = "ovedo@redhat.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/foreman_ovirt/auth_source_ovirts_controller.rb",
    "app/controllers/foreman_ovirt/dashboard_controller.rb",
    "app/controllers/foreman_ovirt/hosts_controller.rb",
    "app/models/foreman_ovirt/auth_source_ovirt.rb",
    "app/models/foreman_ovirt/user_extensions.rb",
    "app/views/foreman_ovirt/auth_source_ovirts/_form.html.erb",
    "app/views/foreman_ovirt/auth_source_ovirts/edit.html.erb",
    "app/views/foreman_ovirt/auth_source_ovirts/index.html.erb",
    "app/views/foreman_ovirt/auth_source_ovirts/new.html.erb",
    "app/views/foreman_ovirt/auth_source_ovirts/welcome.html.erb",
    "app/views/foreman_ovirt/hosts/_overview.html.erb",
    "app/views/foreman_ovirt/hosts/show.html.erb",
    "app/views/foreman_ovirt/hosts/show_graphs.html.erb",
    "app/views/layouts/application_ovirt.html.erb",
    "config/initializers/ovirt_setup.rb",
    "config/routes.rb",
    "foreman_ovirt.gemspec",
    "lib/engine.rb",
    "lib/foreman_ovirt.rb"
  ]
  s.homepage = "http://github.com/oourfali/foreman_ovirt"
  s.licenses = ["GPL-3"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Plugin engine for Foreman-Ovirt integration"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.2.2"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.2.2"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

